# Generated by Django 5.2.3 on 2025-07-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='p2porder',
            table='p2p_order',
        ),
    ]
