# Generated by Django 5.2.3 on 2025-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_trading', '0002_alter_p2porder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2porder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
