# Generated by Django 5.2.3 on 2025-07-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_trading', '0003_p2porder_cancelled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('currency', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'p2p_wallet',
                'unique_together': {('user_id', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('LOCK_ESCROW', 'Lock for Escrow'), ('RELEASE_ESCROW', 'Release from Escrow'), ('CANCEL_ESCROW', 'Cancel Escrow'), ('TRADE_FEE', 'Trade Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('running_balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='p2p_trading.p2porder')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='p2p_trading.wallet')),
            ],
            options={
                'db_table': 'p2p_transaction_model',
                'ordering': ['-created_at'],
            },
        ),
    ]
