# Generated by Django 5.2.3 on 2025-07-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_trading', '0005_remove_p2pprofile_enable_sound_notifications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPaymentMethod',
        ),
    ]
