# Generated by Django 5.2.3 on 2025-07-18 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_trading', '0007_alter_feedback_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('reviewer', 'order')},
        ),
    ]
