# Generated by Django 5.2.3 on 2025-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=255, null=True)),
                ('holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'PaymentMethods',
                'db_table': 'payment_methods',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MainUsers',
                'db_table': 'main_user',
                'ordering': ['username'],
            },
        ),
    ]
