# Generated by Django 5.2.3 on 2025-07-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDashboard', '0002_paymentmethods_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=10)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_wallet',
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='MainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_TO_P2P', 'Transfer to P2P'), ('TRANSFER_FROM_P2P', 'Transfer from P2P'), ('TRANSFER_TO_AUTO', 'Transfer to Auto Trading'), ('TRANSFER_FROM_AUTO', 'Transfer from Auto Trading')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='MainDashboard.mainwallet')),
            ],
            options={
                'db_table': 'main_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
