# Generated by Django 5.2.3 on 2025-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDashboard', '0003_mainwallet_maintransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
