# Generated by Django 5.2.3 on 2025-07-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainDashboard', '0004_mainuser_is_active_mainuser_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='is_superuser',
            new_name='is_staff',
        ),
    ]
